import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'

const API = 'http://localhost:8000'

const AQI_COLOR = (v) => v<=50?'#10b981':v<=100?'#84cc16':v<=200?'#f59e0b':v<=300?'#ef4444':v<=400?'#8b5cf6':'#be185d'
const shortName = (n) => n?.replace(/,\s*Chennai\s*-\s*(CPCB|TNPCB)/,'').trim()

const RISK = {
  low:      { label:'LOW RISK',      c:'#10b981', bg:'rgba(16,185,129,0.08)',  b:'rgba(16,185,129,0.2)'  },
  moderate: { label:'MODERATE RISK', c:'#f59e0b', bg:'rgba(245,158,11,0.08)', b:'rgba(245,158,11,0.2)'  },
  high:     { label:'HIGH RISK',     c:'#ef4444', bg:'rgba(239,68,68,0.08)',  b:'rgba(239,68,68,0.2)'   },
  severe:   { label:'SEVERE RISK',   c:'#8b5cf6', bg:'rgba(139,92,246,0.08)',b:'rgba(139,92,246,0.2)'  },
}

function Nav({ navigate }) {
  return (
    <nav style={{ position:'sticky',top:0,zIndex:100,display:'flex',alignItems:'center',gap:20,padding:'0 48px',height:58,background:'rgba(2,8,23,0.92)',backdropFilter:'blur(20px)',borderBottom:'1px solid rgba(255,255,255,0.06)' }}>
      <div onClick={()=>navigate('/')} style={{ fontFamily:'Space Grotesk,sans-serif',fontWeight:700,fontSize:15,background:'linear-gradient(135deg,#e2eaf4 30%,#0ea5e9)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text',cursor:'pointer',letterSpacing:'-0.02em' }}>
        AeroSense
      </div>
      <div style={{ width:1,height:16,background:'rgba(255,255,255,0.08)' }}/>
      <span style={{ color:'#334155',fontSize:12,letterSpacing:'0.04em' }}>Health Advisories</span>
      <div style={{ flex:1 }}/>
      {[['Dashboard','/dashboard'],['Compare','/compare'],['Enforcement','/enforcement']].map(([l,p])=>(
        <button key={l} onClick={()=>navigate(p)} style={{ background:'none',border:'none',color:'#334155',fontSize:11,fontWeight:600,cursor:'pointer',letterSpacing:'0.07em',fontFamily:'Inter,sans-serif',padding:'5px 10px',borderRadius:6,transition:'all 0.15s' }}
        onMouseOver={e=>{e.currentTarget.style.color='#64748b';e.currentTarget.style.background='rgba(255,255,255,0.04)'}}
        onMouseOut={e=>{e.currentTarget.style.color='#334155';e.currentTarget.style.background='none'}}>
          {l.toUpperCase()}
        </button>
      ))}
    </nav>
  )
}

export default function Advisories() {
  const navigate = useNavigate()
  const [stations, setStations] = useState([])
  const [selected, setSelected] = useState('')
  const [lang,     setLang]     = useState('en')
  const [advisory, setAdvisory] = useState(null)
  const [loading,  setLoading]  = useState(false)
  const [error,    setError]    = useState('')

  useEffect(()=>{
    axios.get(`${API}/api/stations`)
      .then(r=>{ setStations(r.data); if(r.data.length) setSelected(String(r.data[0].id)) })
      .catch(()=>setError('Could not load stations. Is the backend running?'))
  },[])

  const generate = async () => {
    if(!selected) return
    setLoading(true); setError(''); setAdvisory(null)
    try {
      const r = await axios.get(`${API}/api/advisory/${selected}?lang=${lang}`)
      setAdvisory(r.data)
    } catch { setError('Failed to generate advisory. Check your GROQ_API_KEY.') }
    setLoading(false)
  }

  const risk = advisory ? (RISK[advisory.risk_level] || RISK.moderate) : null
  const currentStation = stations.find(s=>String(s.id)===selected)

  return (
    <div style={{ minHeight:'100vh',background:'#020817',color:'#e2eaf4' }}>
      <div style={{ position:'fixed',inset:0,pointerEvents:'none',background:'radial-gradient(ellipse 70% 40% at 50% -10%,rgba(14,165,233,0.06) 0%,transparent 60%)',zIndex:0 }}/>
      <Nav navigate={navigate}/>

      <div style={{ position:'relative',zIndex:1,maxWidth:780,margin:'0 auto',padding:'60px 48px' }}>

        {/* Header */}
        <div className="fade-up" style={{ marginBottom:48 }}>
          <div style={{ color:'#1e3a5f',fontSize:10,letterSpacing:'0.12em',textTransform:'uppercase',fontWeight:700,marginBottom:10 }}>
            AI-Generated · Chennai
          </div>
          <h1 style={{ fontFamily:'Space Grotesk,sans-serif',fontSize:36,fontWeight:700,color:'#e2eaf4',letterSpacing:'-0.03em',marginBottom:12 }}>
            Citizen Health Advisories
          </h1>
          <p style={{ color:'#475569',fontSize:15,lineHeight:1.7 }}>
            Generated by Groq LLaMA 3.3 70B, grounded in live AQI data,<br/>WHO 2021 guidelines, CPCB, and TNPCB standards.
          </p>
        </div>

        {/* Controls card */}
        <div className="fade-up glass" style={{ animationDelay:'60ms',borderRadius:14,padding:'32px 36px',marginBottom:28 }}>
          <div style={{ display:'flex',gap:16,flexWrap:'wrap',alignItems:'flex-end' }}>

            {/* Station */}
            <div style={{ flex:2,minWidth:240 }}>
              <label style={{ display:'block',color:'#334155',fontSize:10,letterSpacing:'0.1em',textTransform:'uppercase',fontWeight:700,marginBottom:10 }}>
                Monitoring Station
              </label>
              <div style={{ position:'relative' }}>
                <select value={selected} onChange={e=>{setSelected(e.target.value);setAdvisory(null)}} style={{
                  width:'100%',background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.09)',
                  borderRadius:8,padding:'11px 36px 11px 14px',color:'#e2eaf4',fontSize:13,outline:'none',cursor:'pointer',
                  transition:'border-color 0.15s',
                }}
                onFocus={e=>e.target.style.borderColor='rgba(14,165,233,0.35)'}
                onBlur={e=>e.target.style.borderColor='rgba(255,255,255,0.09)'}>
                  {stations.map(s=>(
                    <option key={s.id} value={s.id}>
                      {shortName(s.name)} — AQI {Math.round(s.aqi)}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Language */}
            <div>
              <label style={{ display:'block',color:'#334155',fontSize:10,letterSpacing:'0.1em',textTransform:'uppercase',fontWeight:700,marginBottom:10 }}>
                Language
              </label>
              <div style={{ display:'flex',gap:4 }}>
                {[['en','English'],['ta','தமிழ்']].map(([code,label])=>(
                  <button key={code} onClick={()=>{setLang(code);setAdvisory(null)}} style={{
                    padding:'11px 20px',
                    background:lang===code?'rgba(14,165,233,0.12)':'rgba(255,255,255,0.03)',
                    border:`1px solid ${lang===code?'rgba(14,165,233,0.35)':'rgba(255,255,255,0.08)'}`,
                    color:lang===code?'#0ea5e9':'#475569',
                    borderRadius:8,cursor:'pointer',fontSize:13,fontWeight:600,
                    transition:'all 0.15s',
                  }}>
                    {label}
                  </button>
                ))}
              </div>
            </div>

            {/* Generate */}
            <button onClick={generate} disabled={loading||!selected} style={{
              padding:'11px 32px',
              background:loading?'rgba(14,165,233,0.1)':'linear-gradient(135deg,#0ea5e9,#0284c7)',
              color:loading?'#0ea5e9':'#fff',border:loading?'1px solid rgba(14,165,233,0.3)':'none',
              borderRadius:8,fontSize:13,fontWeight:700,cursor:loading?'not-allowed':'pointer',
              letterSpacing:'0.02em',whiteSpace:'nowrap',transition:'all 0.2s',
              boxShadow:loading?'none':'0 8px 24px rgba(14,165,233,0.2)',
            }}>
              {loading ? 'Generating…' : 'Generate Advisory'}
            </button>
          </div>

          {/* Station live chip */}
          {currentStation && (
            <div style={{ marginTop:20,paddingTop:20,borderTop:'1px solid rgba(255,255,255,0.05)',display:'flex',alignItems:'center',gap:16 }}>
              <div style={{ display:'flex',alignItems:'center',gap:8 }}>
                <div style={{ width:8,height:8,borderRadius:'50%',background:AQI_COLOR(currentStation.aqi),boxShadow:`0 0 10px ${AQI_COLOR(currentStation.aqi)}`,flexShrink:0 }}/>
                <span style={{ color:'#334155',fontSize:12 }}>{shortName(currentStation.name)}</span>
              </div>
              <span style={{ fontFamily:'Space Grotesk,sans-serif',color:AQI_COLOR(currentStation.aqi),fontSize:18,fontWeight:700,letterSpacing:'-0.02em' }}>
                AQI {Math.round(currentStation.aqi)}
              </span>
              <span style={{ color:'#334155',fontSize:12 }}>PM2.5 {currentStation.pm25} µg/m³</span>
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="fade-up" style={{ background:'rgba(244,63,94,0.06)',border:'1px solid rgba(244,63,94,0.2)',borderRadius:10,padding:'16px 20px',color:'#f43f5e',fontSize:13,marginBottom:24 }}>
            {error}
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div className="fade-up glass" style={{ borderRadius:14,padding:'60px 32px',textAlign:'center' }}>
            <div style={{ width:36,height:36,border:'3px solid rgba(14,165,233,0.15)',borderTopColor:'#0ea5e9',borderRadius:'50%',animation:'spin 0.7s linear infinite',margin:'0 auto 20px' }}/>
            <div style={{ color:'#334155',fontSize:13 }}>
              Generating {lang==='ta'?'Tamil':'English'} advisory via Groq LLaMA 3.3 70B…
            </div>
          </div>
        )}

        {/* Advisory card */}
        {advisory && !loading && (
          <div className="fade-up" style={{ borderRadius:14,overflow:'hidden',border:`1px solid ${risk.b}`,background:'rgba(8,15,28,0.9)',backdropFilter:'blur(24px)' }}>
            {/* colour stripe */}
            <div style={{ height:3,background:`linear-gradient(90deg,${risk.c},transparent)` }}/>

            {/* Card header */}
            <div style={{ padding:'28px 36px',borderBottom:'1px solid rgba(255,255,255,0.06)' }}>
              <div style={{ display:'flex',justifyContent:'space-between',alignItems:'flex-start',flexWrap:'wrap',gap:16 }}>
                <div>
                  <div style={{ fontFamily:'Space Grotesk,sans-serif',fontSize:22,fontWeight:700,color:'#e2eaf4',letterSpacing:'-0.02em',marginBottom:6 }}>
                    {advisory.station_name}
                  </div>
                  <div style={{ color:'#334155',fontSize:12 }}>
                    {lang==='ta'?'தமிழ் அறிவிப்பு':'English Advisory'} · Generated just now
                  </div>
                </div>
                <div style={{ display:'flex',gap:12,alignItems:'center',flexWrap:'wrap' }}>
                  <div style={{ background:risk.bg,border:`1px solid ${risk.b}`,borderRadius:20,padding:'5px 14px',color:risk.c,fontSize:10,fontWeight:800,letterSpacing:'0.1em' }}>
                    {risk.label}
                  </div>
                  <div style={{ fontFamily:'Space Grotesk,sans-serif',fontSize:32,fontWeight:700,color:AQI_COLOR(advisory.aqi),letterSpacing:'-0.03em' }}>
                    {advisory.aqi}
                    <span style={{ fontSize:13,fontWeight:400,color:'#334155',marginLeft:6 }}>AQI</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Advisory text */}
            <div style={{ padding:'32px 36px' }}>
              <p style={{
                fontSize:lang==='ta'?17:16,
                lineHeight:lang==='ta'?2.0:1.85,
                color:'#c8d6e8',marginBottom:32,
                fontFamily:lang==='ta'?'system-ui,sans-serif':'Inter,sans-serif',
                fontWeight:400,
              }}>
                {advisory.advisory}
              </p>

              {advisory.vulnerable_groups?.length>0 && (
                <>
                  <div style={{ color:'#1e3a5f',fontSize:10,letterSpacing:'0.1em',textTransform:'uppercase',fontWeight:700,marginBottom:14 }}>
                    Vulnerable Groups
                  </div>
                  <div style={{ display:'flex',gap:8,flexWrap:'wrap' }}>
                    {advisory.vulnerable_groups.map((g,i)=>(
                      <span key={i} style={{ background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:20,padding:'5px 16px',color:'#94a3b8',fontSize:12,fontWeight:500 }}>
                        {g}
                      </span>
                    ))}
                  </div>
                </>
              )}
            </div>

            {/* Footer sources */}
            <div style={{ padding:'16px 36px',borderTop:'1px solid rgba(255,255,255,0.05)',display:'flex',gap:24,flexWrap:'wrap' }}>
              {['WHO Air Quality Guidelines 2021','CPCB NAQI Standards','TNPCB Chennai Data'].map((s,i)=>(
                <span key={i} style={{ color:'#1e3a5f',fontSize:11,fontFamily:'JetBrains Mono,monospace' }}>{s}</span>
              ))}
            </div>
          </div>
        )}

        {/* Empty state */}
        {!advisory && !loading && !error && (
          <div className="fade-up glass" style={{ borderRadius:14,padding:'72px 32px',textAlign:'center' }}>
            <div style={{ width:52,height:52,borderRadius:14,background:'rgba(14,165,233,0.08)',border:'1px solid rgba(14,165,233,0.15)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:22,margin:'0 auto 20px' }}>🌫️</div>
            <div style={{ color:'#334155',fontSize:14,lineHeight:1.7 }}>
              Select a station and language,<br/>then click <strong style={{ color:'#475569' }}>Generate Advisory</strong>.
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
